### ISSUE TITLE
Missing 05.07-Support-Vector-Machines.ipynb referenced in 05.14-Image-Features.ipynb

### ISSUE THREAD

**Issue by agirault** [Kitware/ais2-tutorials#2]
Invalid URL:

https://github.com/Kitware/ais2-tutorials/blob/3dcc5f7b2029bc428a41516a98eea61a0884ba6f/notebooks/05.14-Image-Features.ipynb#L137

**Comment by agirault** [comment]
FYI @Erotemic

**Comment by Erotemic** [comment]
See the original notebook for a correctly resolving link: https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.14-Image-Features.ipynb#scrollTo=V7cGoK2WJnVk

We should likely change our version to link to: https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.07-Support-Vector-Machines.ipynb (although it should be noted that we updated our version to the latest scikit-learn API, so the jakevdp version may use outdated APIs in this tutorial). 

@agirault can you submit that PR?
